[package]
name = "workbenches"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
core_document = { path = "../core_document" }
wb_sketch = { path = "wb_sketch" }
wb_part = { path = "wb_part" }


